name: Unit Testing

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - uses: php-actions/composer@8a65f0d3c6a1d17ca4800491a40b5756a4c164f3 # v6.1.2
      
      - name: PHPUnit Tests
        run: vendor/bin/phpunit --bootstrap vendor/autoload.php --configuration test/phpunit.xml --coverage-text
        env:
          XDEBUG_MODE: coverage
          TEST_NAME: Scarlett
          