name: Unit Testing

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: php-actions/composer@8a65f0d3c6a1d17ca4800491a40b5756a4c164f3 # v6.1.2
      
      - name: PHPUnit Tests
        run: vendor/bin/phpunit --bootstrap vendor/autoload.php --configuration test/phpunit.xml --coverage-text
        env:
          XDEBUG_MODE: coverage
          TEST_NAME: Scarlett
          