name: Upload zip to latest release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  upload_zip:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
            token: ${{ secrets.WC_PAT }}

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v3
        with:
          composer-options: "--no-dev"

      - name: Prepare the openedx-commerce directory for the release
        run: |
          make release

      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.6
        with:
          type: 'zip'
          command: 'cd ./openedx-commerce'
          filename: '../openedx-commerce.zip'

      - name: Upload zip to latest release
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.WC_PAT }}
        with:
          file: "openedx-commerce.zip"
          update_latest_release: true
          draft: false
