name: 'WordPress Plugin Check'
on:
  pull_request

jobs:
  check:
    name: Plugin Check
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

    - name: Install Composer dependencies
      uses: ramsey/composer-install@26d8a556604053a9612623447203a691f406fbe6 # v4
      with:
        composer-options: "--no-dev"

    - name: Prepare the openedx-commerce directory for the release
      run: |
        make release

    - name: Run plugin check
      uses: wordpress/plugin-check-action@98a1788320d0add90df2d8183934ecccbc4e05d2 # v1.1.7
      with:
        build-dir: './openedx-commerce'
