name: 'WordPress Plugin Check'
on:
  pull_request

jobs:
  check:
    name: Plugin Check
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

    - name: Install Composer dependencies
      uses: ramsey/composer-install@5c2bcf28d7b060ef3c601d7b476d5430a7b46c27 # v4
      with:
        composer-options: "--no-dev"

    - name: Prepare the openedx-commerce directory for the release
      run: |
        make release

    - name: Run plugin check
      uses: wordpress/plugin-check-action@18573eb38f13543484a1f095672dae3849a4fbb0 # v1.1.6
      with:
        build-dir: './openedx-commerce'
